### PR TITLE
fix kmeansplusplus daal benchmark

### PR DESCRIPTION
**Pull request by fcharras**
Fixes https://github.com/soda-inria/sklearn-numba-dpex/issues/61

### CODE REVIEW

**Comment by fcharras** [comment]
It's also a bit cleaner that what was proposed in https://github.com/soda-inria/sklearn-numba-dpex/pull/62 since the engine accesses low level functions directly while still ensuring appropriate device interfacing.

Also, found out that daal4py does not implements gpu kmean++, only cpy.

`n_local_trials` parameter for `daal4py` is consistent with the default in `sklearn` and ours.

**Review by ogrisel — APPROVED** [review]
LGTM but I wonder why we don't just use:

```python
import sklearnex
sklearnex.patch_sklearn()
```

and then:

```python
sklearnex.unpatch_sklearn()
```

in the benchmark. This way we wouldn't have to maintain our own way to monkeypatch sklearn just for the benchmark. Agreed, we would still need the hack for the missing attribute.

I am find with fixing the current "ext_helper" engine if you prefer.

Can you copy and paste the output of the benchmark script recorded on your machine to a comment of this PR out of curiosity?

**Comment by fcharras** [comment]
It didn't come to mind that the hacky fix in our `daal4py` module would be enough to enable `patch` and `unpatch`, but it's true that `patch` works ! :astonished: I'm still wondering about what else could be broken though. I think I prefer the current way.

**Comment by fcharras** [comment]
Running on my machine with defaults (which includes `kmeans++`):

```
Running Sklearn vanilla lloyd with parameters sample_weight=unary n_clusters=127 data_shape=(263256, 14) max_iter=100 tol=0 ...
Running Sklearn vanilla lloyd ... done in 3.0 s

Running daal4py lloyd CPU with parameters sample_weight=unary n_clusters=127 data_shape=(263256, 14) max_iter=100 tol=0 ...
Running daal4py lloyd CPU ... done in 0.6 s

Running Kmeans numba_dpex lloyd GPU with parameters sample_weight=unary n_clusters=127 data_shape=(263256, 14) max_iter=100 tol=0 ...
Running Kmeans numba_dpex lloyd GPU ... done in 1.7 s
```

**Pull request merged**
